package org.aerogear.connectivity.api;

/**
 * Each instance represents exactly one installation, per phone
 */
public interface MobileApplicationInstance {

    /**
     * The device token (iOS) or registration-id (Android),
     * generated by the actual device 
     */
    void setDeviceToken(String token);
    String getDeviceToken();

    /**
     * The name of the actual OS, used by this "Installation" (e.g. iOS)
     */
    void setMobileOperatingSystem(String os);
    String getMobileOperatingSystem();

    /**
     * The device type of the actual device (e.g. iPad )
     */
    void setDeviceType(String type);
    String getDeviceType();

    /**
     * The version of the actual OS, used by this "Installation" (e.g. 6.1.3)
     */
    void setVersion(String version);
    String getVersion();

    /**
     * Optional identifier, to bridge between business data and devices per "user"
     */
    String getClientIdentifier();
    void setClientIdentifier(String clientIdentifier);
}